thiagopradi/octopus

lib/octopus/persistence.rb

ActiveRecord 4.2 changed the method arguments, which breaks when having octopus.
https://github.com/rails/rails/commit/c80ca4c7803b4e8ed7f125ada9acc6b7c499af5f

Update touch arguments

---

lib/octopus.rb

Rather than using a string manipulation operation, having a file object to join paths. 
It is also recommended because this can give user power to define his own directory from where shards settings should be picked up.

File path addition done using file object rather than manipulating string.

---

ar-octopus.gemspec
lib/octopus/association_shard_tracking.rb
spec/octopus/association_shard_tracking_spec.rb

Here's an attempt to fix #322 
This stack level too deep error happens when `respond_to?` being called on unloaded grouped AR::Relation.
This patch changes the code to directly reference the instance variable `@association` rather than using a public method.
This approach is indeed a little bit adhoc, but this should work on [AR 5](https://github.com/rails/rails/blob/bf4f739e0793c048cdba02e46c76fe2f46202da4/activerecord/lib/active_record/association_relation.rb#L8-L10), [4.2](https://github.com/rails/rails/blob/4-2-stable/activerecord/lib/active_record/association_relation.rb#L8-L10), [4.1](https://github.com/rails/rails/blob/4-1-stable/activerecord/lib/active_record/association_relation.rb#L8-L10), [4.0](https://github.com/rails/rails/blob/4-0-stable/activerecord/lib/active_record/associa …

Fix stack level too deep on grouped calculation

---

lib/octopus.rb
lib/octopus/railtie.rb

When some non rails project depends on actionmailer, the rails-sanitizer-html gem is loaded and the Rails module is created, this way to check `Rails` module is not a good idea... 
Take a look this issue https://github.com/rails/rails-html-sanitizer/issues/25 
A way to solve this is to check for specific methods instead `Rails` module.

Fix Rails module check, to avoid issues with non rails projects

---

lib/octopus.rb
lib/octopus/proxy.rb

The memory_profiler gem indicates that these string allocations make up a significant
proportion of our overall allocations on our production Rails app

Avoid unnecessary string allocations

---

lib/octopus/abstract_adapter.rb

As of ruby 2.0, `Module` supports `#prepend`, which allows derivation-style overriding using `super`, rather than the old-style insertion and `alias_method_chain` hack.  See, e.g., [this blog post](http://dev.af83.com/2012/10/19/ruby-2-0-module-prepend.html)
Aside from being generally cleaner, and the direction [rails is going](http://weblog.rubyonrails.org/2015/3/27/this-week-in-rails-goodbye-alias_method_chain-postgresql-typecasting-and-more/), this PR specifically fixes the inifinite recursion reported in SchemaPlus/schema_monkey#4

Replace Module#include & alias_method_chain with Module#prepend & super

---

lib/octopus/proxy.rb
spec/octopus/replicated_slave_grouped_spec.rb

This currently has a curious behaviour:
```ruby
Octopus.using(:slave_group => :mygroup) do ... end
```
Only the first query in the block would actually go to the slave group, and all others to `:master`. Also, it isn't nestable.
This fixes both issues, hopefully!

Allows slave groups to be used in Octopus.using blocks

---

README.mkdn
lib/octopus.rb
lib/octopus/proxy.rb

Good for using within ```db/seeds.rb```.
```using_all``` filters out duplicates in case the master shard is one of the shards in ```config/shards.yml``` (see tchandy/octopus#270).
Also, ```Octopus::Proxy#send_queries_to_multiple_shards``` should return the results.

add #using_group and #using_all ability

---

lib/octopus.rb
lib/octopus/load_balancing/round_robin.rb
lib/octopus/proxy.rb
lib/octopus/slave_group.rb

This feature is a minor change to support people adding their own custom load balancers for slave groups (Octopus::LoadBalancing::RoundRobin is still the default load balancer). In order to do so, you do
Octopus.load_balancer = MyCustomLoadBalancer where MyCustomLoadBalancer is a class that implements an initialize method accepting a slave group and a next method accepting an optional hash of options. 
In this feature, users also have the ability to pass options to their custom load balancers by specifying a key called load_balancer_options like in the following example:
Octopus.using(:slave_group => :slave_group_a, :load_balance_options => {:enforce_best_available => true}){Customer.first}
I am currently using this to be able to have a custom load balancer that periodically checks the …

add support for being able to plug in custom load balancer

---

lib/octopus/relation_proxy.rb
spec/octopus/relation_proxy_spec.rb

A change in Ruby 2.3 made it so that Marshal.dump does not work on things that inherit from BasicObject unless they define a respond_to? method: https://bugs.ruby-lang.org/issues/12353

workaround for Marshal.dump to work in Ruby 2.3

---

lib/octopus/association_shard_tracking.rb
spec/octopus/association_shard_tracking_spec.rb

The new error message includes the record, current_shard and the
record's current_shard. This should help users debug which record is
mismatched as well as what shards are involved in the issue.

Create a custom exception for mismatched shards on associations

---

lib/octopus/log_subscriber.rb
lib/octopus/migration.rb
lib/octopus/model.rb
lib/octopus/shard_tracking.rb

Preferably would be to use `prepend` method, but since I'm unable to run specs (as it requires all db types), I'm using straightforward `alias_method`

Remove deprecated alias_method_chain

---

lib/octopus/model.rb
lib/octopus/proxy.rb

The semantics around choosing the `current_shard` on a model during `set_current_shard` have caused bugs in our application. This is because `current_shard` has been set the `last_current_shard` reference on the `Octopus::Proxy` object. 
It doesn't ever make sense to set the `current_shard` on a new object equal to the last shard that `Octopus::Proxy` connected to. It should always be set to the `Octopus::Proxy`'s `current_shard` object.
[The commit that adds the `last_current_shard`](https://github.com/thiagopradi/octopus/commit/bd80853d97cf928a4ff25b6444b0ff461f332856) reference to the `Octopus::Proxy` object provides no explanation or insight as to why it was added. Additionally no specs exist around `last_current_shard`.
Therefore it seems as though it should just be removed, and will …

Removing `last_current_shard` reference

---

spec/octopus/model_spec.rb
spec/octopus/octopus_spec.rb

An error message or a class has to be provided for the RSpec
matcher 'raise_error'. This commit fixes those warnings.
This is one of those warnings:
```shell
WARNING: Using the `raise_error` matcher without providing a specific error or
message risks false positives, since `raise_error` will match when Ruby raises a
`NoMethodError`, `NameError` or `ArgumentError`, potentially allowing the
expectation to pass without even executing the method you are intending to call.
Actual error raised was #<RuntimeError: Nonexistent Shard Name: crazy_shard>.
Instead consider providing a specific error class or message. This message can be 
suppressed by setting:
`RSpec::Expectations.configuration.on_potential_false_positives = :nothing`.
Called from /Users/projects/spec/octopus/octopus_spec.rb:40:in …
```

Fix RSpec 'raise_error' warnings

---

init.rb
rails/init.rb

Support for them was dropped long time ago from Rails.

Remove not used init Rails files.

---

lib/octopus/load_balancing/round_robin.rb
spec/octopus/load_balancing/round_robin_spec.rb

Currently, if you run an Octopus-enabled application with a shards.yml that is misconfigured to define zero slaves in the appropriate slave group, you get this error:
```
<path_to_gems>/ar-octopus-0.9.0/lib/octopus/load_balancing/round_robin.rb:15:in `%': divided by 0 (ZeroDivisionError)
from /home/ubuntu/quottly-ng/.bundle/ruby/2.3.0/gems/ar-octopus-0.9.0/lib/octopus/load_balancing/round_robin.rb:15:in `next'
from /home/ubuntu/quottly-ng/.bundle/ruby/2.3.0/gems/ar-octopus-0.9.0/lib/octopus/proxy.rb:441:in `send_queries_to_selected_slave'
```
This isn't particularly hard to track down, but it could be more helpful. 
I haven't yet run any tests here; but will run tests & update presently.

Raise helpful error if no slaves are available

---

lib/octopus/proxy.rb

Hi Folks,
This PR focus on removing (or at least deprecating) the method_missing from Octopus::Proxy. This is a move to improve the stability and increase the predictability of the gem's behavior. Hopefully this will be a step to have less bugs in the future.
Thiago

Removing method missing

---

lib/octopus.rb
lib/octopus/association_shard_tracking.rb
spec/support/database_models.rb

Summary
-----
This PR fixes a missed change when adding Octopus support for Rails 5.1. In 5.1, the options argument in the method `has_and_belongs_to_many` was changed from `options = {}` to `**options`.  Due to the argument inconsistency, supplied options to `has_and_belongs_to_many`  are ignored 
@thiagopradi Please review, test and merge. This fixes my integration issues when using Rails 5.1.

Rails 5.1 fix -- has_and_belongs_to_many

---

spec/octopus/octopus_spec.rb
spec/octopus/proxy_spec.rb
spec/support/database_connection.rb
spec/support/database_models.rb

I tried to use a MySQL user (with no password :-() for the Octopus
specs, however, I need to make these adjustments to get a green build.
I am sure there is a better way to set up the configuration file, but this now
fixes the immediate problem.

Use the MYSQL_USER environment variable in all the specs

---

lib/octopus/scope_proxy.rb
spec/octopus/relation_proxy_spec.rb

We've been bitten a few times by this bug.
To demonstrate:
```
relation = Item.using(:canada).where(id: 1)
puts relation.to_sql
=> SELECT `items`.* FROM `items` WHERE `items`.`id` = 1
new_relation = relation.where(id: 2)
puts relation.to_sql
=> SELECT `items`.* FROM `items` WHERE `items`.`id` = 1 AND `items`.`id` = 2
```
We don't expect `relation` to have changed.

Don't alter underlying AR relations when chaining

---

lib/octopus.rb
lib/octopus/proxy.rb
lib/octopus/query_cache_for_shards.rb
spec/octopus/query_cache_for_shards_spec.rb

The `enable_query_cache!` and `disable_query_cache!` methods are moved to `ConnectionProxy` from `Connection` on Rails 5.
Currently Octopus only hijacks `Connection`'s methods to turn on/off the query cache for all shards, but it should hook `ConnectionProxy` on Rails5.
This fixes the issue that the query cache is shared beyond requests. Resolves #405.

Fix query cache enable/disable methods proxy on Rails5.x

---

lib/octopus/relation_proxy.rb
lib/octopus/scope_proxy.rb
spec/octopus/association_shard_tracking_spec.rb
spec/octopus/scope_proxy_spec.rb

Currently, when Enumerable methods that takes block are called for
relations scoped from a shard, ActiveRecord::Relation object is
populated out of the shard, so the records from the master are used.
e.g.:
```
User.using(:brazil).first.projects.where(id: ids).map(&:name)
```
will execute the query on the `:master` shard, instead of `:brazil`.
This patch lists up the Enumerable methods that are not redefined
by ActiveRecord classes, and redirect them to objects taken from
the correct shards.
This will resolve #478.

Fix association shard tracking combined with enum method chain in Rails5

---

ar-octopus.gemspec
gemfiles/rails4.gemfile
gemfiles/rails41.gemfile

Currently, some CI test patterns are failing. This is because by recent update of mysql2 gem version specification in the commit d87f599. The `mysql2` gem version specified in `ar-octopus.gemspec` is conflicting with `rails4.gemspec` / `rails41.gemspec` specification.
This fixes the issue by expanding the version specification range of `mysql2` gem, and specifying the gem version referred by each version of activerecord explicitly.

Expand mysql2 gem version to fix CI test failures

---

lib/octopus/query_cache_for_shards.rb
spec/octopus/query_cache_for_shards_spec.rb

The new QueryCacheForShards fix for Rails 5 raises an exception when running in an environment Octopus is not enabled for.
The exception raised:
```
NoMethodError:
undefined method `shards' for #<ActiveRecord::ConnectionAdapters::Mysql2Adapter>
```
(or whatever adapter you are using)
You can remove the `Octopus.enabled?` check from my change and the tests I added will show the exception.

Fix QueryCacheForShards breaking in environments where Octopus is not enabled

---

lib/octopus/relation_proxy.rb
spec/octopus/model_spec.rb
spec/octopus/relation_proxy_spec.rb

Currently, if a batch method like `find_each` or `find_in_batches` is called without a block `Octopus::RelationProxy` will send `method` wrapped in `run_on_shard` to the `ActiveRecord::Relation`, but since the queries are not executed immediately, execution flow will leave the block and the shard will be immediately restored. When the `Enumerator` is used later, the relation will execute queries on the `:master` shard.
Instead we can return a new `Enumerator` and iterate the results from within a `run_on_shard` at its iteration time.

Support lazy batches

---

lib/octopus/scope_proxy.rb
spec/octopus/model_spec.rb

Currently, using a transaction reassigns the `@klass` variable to the return value of the transaction.  This is problematic when assigning the class to a variable for using in scopes.  For example:
```
scope = User.using(:shard_1)
scope.transaction do
123
end
puts scope # result is 123
```
With this fix, `scope` will stay as the `User` class.

bugfix: transaction should not reassign @klass variable

---

ar-octopus.gemspec
lib/octopus/relation_proxy.rb
spec/octopus/model_spec.rb

This is a bug fix.
Currently,  Enum method after `where.not` can't maintain current shard. For example:
```
User.using(:brazil).where.not(:name => 'User2').find_each { }
```
`find_each` should use `brazil` shard. but now it uses default shard because of a bug.
Because `find_each` is executed with `Octopus::RelationProxy` as the `self`. But It should be executed with  `Octopus::ScopeProxy`  to maintain current shard.

Mantain current shard with enum method after where.not

---

README.mkdn

Drop antiquated `slave` terminology in favor of `read_replica` in examples.

Drop antiquated slave terminology in favor of read_replica in examples.
